@echo off
echo Starting TradingView...
powershell -Command "Start-Process 'C:\Program Files\WindowsApps\TradingView.Desktop_3.1.0.7818_x64__n534cwy3pjxzj\TradingView.exe' -ArgumentList '--remote-debugging-port=9222'"
timeout /t 15
echo Starting dashboard...
node dashboard/server.js
